# Generated by Django 2.0 on 2017-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171224_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
