# Generated by Django 2.0 on 2017-12-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('term', models.CharField(max_length=5)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Instructor')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='term',
        ),
        migrations.AlterField(
            model_name='comment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Section'),
        ),
    ]
