# Generated by Django 2.0 on 2018-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171225_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrating',
            name='flag',
            field=models.CharField(choices=[('M', 'Not Useful'), ('I', 'Inappropriate')], default=None, max_length=1, null=True),
        ),
    ]
