# Generated by Django 2.0 on 2018-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiration',
            field=models.DateTimeField(db_index=True),
        ),
    ]
